apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdfsign-svc.fullname" . }}
  labels:
    {{- include "pdfsign-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "pdfsign-svc.selectorLabels" . | nindent 4 }}
