apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: pdfsign-svc
    newName: registry.example.org/pdfsign-svc
    newTag: "0.1.0"
